require("joo.plugins-setup")
require("joo.core.options")
require("joo.core.keymaps")
require("joo.plugins.pywal")
require("joo.plugins.nvim-tree")
require("joo.plugins.which-key")
require("joo.plugins.lualine")
require("joo.plugins.lastplace")
require("joo.plugins.autopairs")
require("joo.plugins.gitsigns")
require("joo.plugins.code-runner")
require("joo.plugins.nvim-cokeline")
require("joo.plugins.mini")
require("joo.plugins.treesitter")
require("joo.plugins.nvim-cmp")
require("joo.plugins.luasnip")

