#! /bin/sh

sxhkd &
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
if xrandr -q | grep 'HDMI-1 connected' >/dev/null 2>&1; then
    xrandr --output eDP-1 --primary --output HDMI-1 --left-of eDP-1
    # autorandr -c
    bspc monitor eDP-1 -d 2 4 8 10
    bspc monitor HDMI-1 -d 1 3 5 6 7 9
fi

wmname LG3D
xrdb ~/.Xresources &
~/.config/polybar/launch.sh &
picom --config ~/.config/picom.conf -b --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 &
nm-applet &
xmodmap -e "clear Lock" -e 'keycode 0x42 = Escape' &
feh --bg-scale ~/Pictures/wallpapers/mountains.png &
pacmd set-default-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink


bspc config top_padding         2
bspc config border_width        2
bspc config window_gap          10

bspc config focused_border_color F5A97F

bspc config split_ratio          0.6
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       false

bspc rule -a Zathura state=floating rectangle=1000x1250+1400+100
bspc rule -a mpv state=floating rectangle=854x480+150+600
bspc rule -a steam_app_6910 state=floating
bspc rule -a Skype state=floating
bspc rule -a Yad state=floating
bspc rule -a Blender state=floating
bspc rule -a rebound state=floating
bspc rule -a cube state=floating
bspc rule -a Cube state=floating
bspc rule -a Toplevel state=floating
bspc rule -a feh state=floating
bspc rule -a zoom state=floating
bspc rule -a Msgcompose state=floating
bspc rule -a thunderbird state=floating
bspc rule -a Mailspring state=floating
bspc rule -a uk-ac-starlink-topcat-Driver state=floating
bspc rule -a Ds9.tcl state=floating layer=above
bspc rule -a Lutris state=floating
bspc rule -a ESOQuery.py state=floating
bspc rule -a Ryujinx state=floating
bspc rule -a SPHEREQuery.py state=floating
bspc rule -a tsmapplication.exe state=floating
bspc rule -a battle.net.exe state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Matplotlib state=floating layer=above
bspc rule -a herschel-ia-gui-apps-HipeStarter state=floating
bspc rule -a " " state=floating

bspc rule -a Firefox desktop='1'
bspc rule -a thunderbird desktop='2' follow=on
bspc rule -a GoPanda2 desktop='8'
bspc rule -a Sabaki desktop='7'
# bspc rule -a mpv desktop='8'
bspc rule -a Gimp desktop='9' state=floating follow=on
bspc rule -a spotify desktop='10'
